apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clustersecret
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: clustersecret
spec:
  project: default
  source:
    repoURL: https://charts.clustersecret.io
    chart: cluster-secret
    targetRevision: 0.4.1
  destination:
    name: in-cluster
    namespace: clustersecret
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
