apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi-retain
  volumeMode: Filesystem
  csi:
    driver: nfs.csi.k8s.io
    volumeAttributes:
      server: 192.168.1.10
      share: /kubedata
      subDir: persistent-data/mysql # This is the directory in the shared folder on NFS server that I want it to create
    volumeHandle: mysql-pv
  mountOptions:
    - nfsvers=4.1
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: YWRtaW4=
  MYSQL_DATABASE: b3JkZXJfc2VydmljZQ==
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-csi-retain
  volumeMode: Filesystem
  volumeName: mysql-pv
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: mysql-init-db
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS b3JkZXJfc2VydmljZQ==;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          envFrom:
            - secretRef:
                name: mysql-secret
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: mysql-init-db
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: mysql-init-db
          configMap:
            name: mysql-init-db
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
