apiVersion: v1
kind: PersistentVolume
metadata:
  name: jcr-artifactory-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 190Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi-registry
  volumeMode: Filesystem
  csi:
    driver: nfs.csi.k8s.io
    volumeAttributes:
      server: 192.168.1.11
      share: /jcr
      subDir: jcr-artifactory
    volumeHandle: jcr-artifactory
  mountOptions:
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jcr-artifactory-pvc
  namespace: artifactory-jcr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 190Gi
  storageClassName: nfs-csi-registry
  volumeMode: Filesystem
  volumeName: jcr-artifactory-pv