apiVersion: clustersecret.io/v1
kind: ClusterSecret
metadata:
  name: jcr-image-pull-secret
  namespace: artifactory-jcr
matchNamespace:
  - '.*'
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <base64-encoded-docker-config-json>
