apiVersion: v1
kind: Namespace
metadata:
  name: cloudflared
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudflared
  name: cloudflared-deployment
  namespace: cloudflared
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: cloudflared
  template:
    metadata:
      creationTimestamp: null
      labels:
        pod: cloudflared
    spec:
      containers:
      - command:
        - cloudflared
        - tunnel
        - --metrics
        - 0.0.0.0:2000
        - run
        args:
        - --token
        - eyJhIjoiMjMyYjMwOGEzNmJkOTgzNGFkYWQxMGFlNjFkMDI5YTciLCJ0IjoiN2JmODhlZTAtZTBhZC00ZGY0LWIyMGQtNDlmODBkOWNhMzIwIiwicyI6IllqSTFaVGs1Wm1ZdE1qUmlaaTAwT1RreUxXRTVaamd0TlRnME0yRXpObUU0WWpCaiJ9
        image: cloudflare/cloudflared:latest
        name: cloudflared
        livenessProbe:
          httpGet:
            path: /ready
            port: 2000
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
