apiVersion: apps/v1
kind: Deployment
metadata:
  name: lunalovegood-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: lunalovegood
  replicas: 2
  template:
    metadata:
      labels:
        app: lunalovegood
    spec:
      containers:
        - name: lunalovegood
          image: jcr.lunalovegood.dev/docker/template-service:5cb4e9a790d1fd67b20ff1fbb880f8017a2c3dd0
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: jcr-image-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: lunalovegood-service
  namespace: default
spec:
  selector:
    app: lunalovegood
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lunalovegood-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
    - host: lunalovegood.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lunalovegood-service
                port:
                  number: 80
  tls:
    - hosts:
        - lunalovegood.dev
      secretName: lunalovegood-dev-tls
